/**
 * Pixel-art character sprite system — loads from PNG sprite sheets.
 *
 * Each agent has a sprite sheet at /sprites/agents/<name>.png
 * Sheet layout: 112×96 pixels (7 cols × 3 rows)
 *   - Columns (frames): walk0(idle), walk1, walk2, type0, type1, read0, read1
 *   - Rows (directions): down, up, right
 *   - Each frame: 16×32 pixels
 *
 * Left direction is generated by flipping right sprites.
 * SpriteData = string[][] (rows of hex color strings, '' = transparent)
 */

import type { AgentAppearance, AgentDirection, AgentId } from '@/types/agent';

export type SpriteData = string[][];

// ═══════════════════════════════════════════════════════════════
// Constants matching the PNG sprite sheet layout
// ═══════════════════════════════════════════════════════════════

const FRAME_W = 16;
const FRAME_H = 32;
const FRAMES_PER_ROW = 7;
const DIRECTION_ROWS: ('down' | 'up' | 'right')[] = ['down', 'up', 'right'];
const PNG_ALPHA_THRESHOLD = 2;

// ═══════════════════════════════════════════════════════════════
// Color utilities
// ═══════════════════════════════════════════════════════════════

function darken(hex: string, amount: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const f = 1 - amount;
  return (
    '#' +
    Math.max(0, Math.floor(r * f)).toString(16).padStart(2, '0') +
    Math.max(0, Math.floor(g * f)).toString(16).padStart(2, '0') +
    Math.max(0, Math.floor(b * f)).toString(16).padStart(2, '0')
  );
}

function rgbaToHex(r: number, g: number, b: number, a: number): string {
  if (a < PNG_ALPHA_THRESHOLD) return '';
  return (
    '#' +
    r.toString(16).padStart(2, '0') +
    g.toString(16).padStart(2, '0') +
    b.toString(16).padStart(2, '0')
  );
}

// ═══════════════════════════════════════════════════════════════
// PNG loading & parsing
// ═══════════════════════════════════════════════════════════════

interface LoadedCharacterData {
  down: SpriteData[];
  up: SpriteData[];
  right: SpriteData[];
}

/**
 * Load a PNG image and return its ImageData.
 */
function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load sprite: ${src}`));
    img.src = src;
  });
}

/**
 * Parse an agent's sprite sheet PNG into per-direction frame arrays.
 */
async function loadCharacterSheet(agentName: string): Promise<LoadedCharacterData> {
  const img = await loadImage(`/sprites/agents/${agentName}.png`);

  // Draw to offscreen canvas and read pixel data
  const canvas = document.createElement('canvas');
  canvas.width = img.width;
  canvas.height = img.height;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(img, 0, 0);
  const imageData = ctx.getImageData(0, 0, img.width, img.height);
  const { data, width } = imageData;

  const result: LoadedCharacterData = { down: [], up: [], right: [] };

  for (let dirIdx = 0; dirIdx < DIRECTION_ROWS.length; dirIdx++) {
    const dirName = DIRECTION_ROWS[dirIdx];
    const rowOffset = dirIdx * FRAME_H;

    for (let f = 0; f < FRAMES_PER_ROW; f++) {
      const colOffset = f * FRAME_W;
      const sprite: SpriteData = [];

      for (let y = 0; y < FRAME_H; y++) {
        const row: string[] = [];
        for (let x = 0; x < FRAME_W; x++) {
          const px = ((rowOffset + y) * width + (colOffset + x)) * 4;
          const r = data[px];
          const g = data[px + 1];
          const b = data[px + 2];
          const a = data[px + 3];
          row.push(rgbaToHex(r, g, b, a));
        }
        sprite.push(row);
      }

      result[dirName].push(sprite);
    }
  }

  return result;
}

// ═══════════════════════════════════════════════════════════════
// Sprite flipping
// ═══════════════════════════════════════════════════════════════

function flipHorizontal(sprite: SpriteData): SpriteData {
  return sprite.map((row) => [...row].reverse());
}

// ═══════════════════════════════════════════════════════════════
// Public API
// ═══════════════════════════════════════════════════════════════

export interface CharacterSpriteSet {
  idle: Record<AgentDirection, SpriteData>;
  walk: Record<AgentDirection, [SpriteData, SpriteData, SpriteData]>;
}

// Cache loaded sprite sets by agent name
const spriteCache = new Map<string, CharacterSpriteSet>();

// Loading promises to avoid double-loading
const loadingPromises = new Map<string, Promise<CharacterSpriteSet>>();

// Map agent appearance to agent name for PNG lookup
const AGENT_NAME_MAP: Record<string, AgentId> = {};
function registerAgentName(appearance: AgentAppearance, name: AgentId): void {
  AGENT_NAME_MAP[appearanceKey(appearance)] = name;
}

function appearanceKey(appearance: AgentAppearance): string {
  return `${appearance.hairColor}|${appearance.outfitColor}|${appearance.skinColor}`;
}

/**
 * Register all agent name-to-appearance mappings.
 * Called once at startup with the agent profiles.
 */
export function registerAgentAppearances(
  agents: { id: AgentId; appearance: AgentAppearance }[],
): void {
  for (const agent of agents) {
    registerAgentName(agent.appearance, agent.id);
  }
}

/**
 * Build a CharacterSpriteSet from loaded PNG data.
 */
function buildSpriteSet(data: LoadedCharacterData): CharacterSpriteSet {
  // Frame indices in the sheet:
  // 0=idle(walk0), 1=walk1, 2=walk2, 3=type0, 4=type1, 5=read0, 6=read1
  const downIdle = data.down[0];
  const downW1 = data.down[1];
  const downW2 = data.down[2];

  const upIdle = data.up[0];
  const upW1 = data.up[1];
  const upW2 = data.up[2];

  const rightIdle = data.right[0];
  const rightW1 = data.right[1];
  const rightW2 = data.right[2];

  const leftIdle = flipHorizontal(rightIdle);
  const leftW1 = flipHorizontal(rightW1);
  const leftW2 = flipHorizontal(rightW2);

  return {
    idle: {
      down: downIdle,
      up: upIdle,
      left: leftIdle,
      right: rightIdle,
    },
    walk: {
      down: [downIdle, downW1, downW2],
      up: [upIdle, upW1, upW2],
      left: [leftIdle, leftW1, leftW2],
      right: [rightIdle, rightW1, rightW2],
    },
  };
}

/**
 * Preload all agent sprite sheets. Call once at startup.
 */
export async function preloadAllSprites(): Promise<void> {
  const names: AgentId[] = ['luna', 'max', 'ava', 'sam', 'rio'];
  await Promise.all(names.map((name) => preloadSprite(name)));
}

/**
 * Preload a single agent's sprite sheet.
 */
async function preloadSprite(agentName: AgentId): Promise<CharacterSpriteSet> {
  const cached = spriteCache.get(agentName);
  if (cached) return cached;

  const existing = loadingPromises.get(agentName);
  if (existing) return existing;

  const promise = loadCharacterSheet(agentName).then((data) => {
    const sprites = buildSpriteSet(data);
    spriteCache.set(agentName, sprites);
    loadingPromises.delete(agentName);
    return sprites;
  });

  loadingPromises.set(agentName, promise);
  return promise;
}

/**
 * Get character sprites for an agent. Returns cached PNG-based sprites.
 * Falls back to a placeholder if not yet loaded.
 *
 * Maintains the same synchronous interface for compatibility with the renderer.
 */
export function getCharacterSprites(appearance: AgentAppearance): CharacterSpriteSet {
  const key = appearanceKey(appearance);
  const agentName = AGENT_NAME_MAP[key];

  if (agentName) {
    const cached = spriteCache.get(agentName);
    if (cached) return cached;
  }

  // Try by agent name directly (might be cached from preload)
  for (const [name, set] of spriteCache.entries()) {
    // Return any cached set as placeholder while loading
    if (set) return set;
  }

  // Return empty placeholder — preloadAllSprites should be called first
  return createEmptyPlaceholder();
}

function createEmptyPlaceholder(): CharacterSpriteSet {
  const empty: SpriteData = Array.from({ length: FRAME_H }, () =>
    Array(FRAME_W).fill(''),
  );
  return {
    idle: { down: empty, up: empty, left: empty, right: empty },
    walk: {
      down: [empty, empty, empty],
      up: [empty, empty, empty],
      left: [empty, empty, empty],
      right: [empty, empty, empty],
    },
  };
}

// ═══════════════════════════════════════════════════════════════
// Accessory overlay drawing (drawn on top of the sprite)
// ═══════════════════════════════════════════════════════════════

export function drawAccessoryOverlay(
  ctx: CanvasRenderingContext2D,
  accessory: string,
  worldX: number,
  worldY: number,
  zoom: number,
  outfitColor: string,
): void {
  const z = zoom;

  switch (accessory) {
    case 'glasses':
    case 'glasses_round':
    case 'glasses_neon': {
      const color =
        accessory === 'glasses_neon'
          ? '#10b981'
          : accessory === 'glasses_round'
            ? '#92400e'
            : '#374151';
      ctx.fillStyle = color;
      ctx.fillRect(worldX + 3 * z, worldY + 7 * z, 3 * z, 1 * z);
      ctx.fillRect(worldX + 8 * z, worldY + 7 * z, 3 * z, 1 * z);
      ctx.fillRect(worldX + 6 * z, worldY + 7 * z, 2 * z, 1 * z);
      break;
    }
    case 'headphones':
    case 'headphones_pink': {
      const color = accessory === 'headphones_pink' ? '#db2777' : '#222233';
      ctx.fillStyle = color;
      ctx.fillRect(worldX + 2 * z, worldY + 2 * z, 1 * z, 4 * z);
      ctx.fillRect(worldX + 13 * z, worldY + 2 * z, 1 * z, 4 * z);
      ctx.fillRect(worldX + 3 * z, worldY + 1 * z, 10 * z, 1 * z);
      break;
    }
    case 'hat':
    case 'hat_cap':
    case 'hat_beanie':
    case 'hat_cowboy': {
      const color =
        accessory === 'hat_beanie'
          ? '#7c3aed'
          : accessory === 'hat_cowboy'
            ? '#78350f'
            : darken(outfitColor, 0.2);
      ctx.fillStyle = color;
      ctx.fillRect(worldX + 4 * z, worldY + 0 * z, 8 * z, 2 * z);
      ctx.fillRect(worldX + 3 * z, worldY + 1 * z, 10 * z, 1 * z);
      break;
    }
    case 'badge':
    case 'badge_red': {
      ctx.fillStyle = accessory === 'badge_red' ? '#dc2626' : '#fbbf24';
      ctx.fillRect(worldX + 7 * z, worldY + 13 * z, 2 * z, 3 * z);
      break;
    }
    case 'tie':
    case 'tie_blue': {
      ctx.fillStyle = accessory === 'tie_blue' ? '#2563eb' : '#dc2626';
      ctx.fillRect(worldX + 7 * z, worldY + 11 * z, 2 * z, 6 * z);
      break;
    }
    case 'scarf':
    case 'scarf_green': {
      ctx.fillStyle = accessory === 'scarf_green' ? '#16a34a' : '#7c3aed';
      ctx.fillRect(worldX + 3 * z, worldY + 10 * z, 10 * z, 2 * z);
      break;
    }
  }
}
